CREATE TABLE userinfo (
   rid VARCHAR(200) PRIMARY KEY,
   user_name VARCHAR(200) NOT NULL,
   phone VARCHAR(200) NOT NULL,
   id_card VARCHAR(200) NOT NULL,
   password VARCHAR(200) NOT NULL
);


CREATE TABLE IF NOT EXISTS roleinfo (
  rid VARCHAR(200) PRIMARY KEY,
  role_name VARCHAR(200) NOT NULL,
  phone VARCHAR(200) NOT NULL,
  id_card VARCHAR(200) NOT NULL
);
